version: '3.8'
services:
  orderservice:
    build: ./Microservices/Orderservice
    image: microservices/orderservice
    ports:
     - "5000:80"
    links:
     - customerservice
  customerservice:
   build: ./Microservices/CustomerService
   image: microservices/customerservice
   ports:
    - "5001:8080"
  monolithic:
   build: ./MonolithicApp
   image: monolithicapp
   ports:
    - "80:80"